import type { Plugin } from "vite";
import { promises as fs } from "fs";
import path from "path";

const VIRTUAL_ID = "virtual:intelligence-manifest";
const RESOLVED_ID = "\0" + VIRTUAL_ID;

const CONTENT_DIR = path.resolve(__dirname, "../src/content/intelligence");

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else if (entry.name.endsWith(".mdx")) out.push(p);
  }
  return out;
}

async function buildManifest(): Promise<string> {
  const files = await walk(CONTENT_DIR);
  const entries: { rel: string; raw: string }[] = [];

  for (const file of files) {
    const src = await fs.readFile(file, "utf8");
    const m = src.match(/export\s+const\s+frontmatter\s*=\s*(\{[\s\S]*?\n\});/);
    if (!m) continue;
    // Use absolute paths so dynamic imports resolve from the virtual module.
    entries.push({ rel: file, raw: m[1] });
  }

  // Emit JS module with eager frontmatter + lazy loaders keyed by relative path.
  const lines = [
    "// Auto-generated by vite-plugins/intelligence-manifest.ts",
    "export const FRONTMATTERS = [",
    ...entries.map(
      (e) => `  { __path: ${JSON.stringify(e.rel)}, ...${e.raw} },`
    ),
    "];",
    "",
    "export const LOADERS = {",
    ...entries.map(
      (e) => `  ${JSON.stringify(e.rel)}: () => import(${JSON.stringify(e.rel)}),`
    ),
    "};",
    "",
  ];
  return lines.join("\n");
}

export function intelligenceManifestPlugin(): Plugin {
  let cache: string | null = null;

  return {
    name: "deepgrain:intelligence-manifest",
    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
    },
    async load(id) {
      if (id !== RESOLVED_ID) return;
      if (!cache) cache = await buildManifest();
      return cache;
    },
    async handleHotUpdate(ctx) {
      if (ctx.file.includes("/content/intelligence/") && ctx.file.endsWith(".mdx")) {
        cache = null;
        const mod = ctx.server.moduleGraph.getModuleById(RESOLVED_ID);
        if (mod) ctx.server.moduleGraph.invalidateModule(mod);
      }
    },
  };
}
