// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-intelligence.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var search_intelligence_default = defineTool({
  name: "search_intelligence",
  title: "Search Deepgrain Intelligence",
  description: "Search the Deepgrain Intelligence library (essays, guides, glossary, answers) for a keyword or phrase. Returns matching article slugs with a short snippet around the first hit.",
  inputSchema: {
    query: z.string().min(2).describe("Keyword or short phrase to search for."),
    limit: z.number().int().min(1).max(20).optional().describe("Maximum number of matching articles to return. Default 8.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const max = limit ?? 8;
    const res = await fetch("https://deepgrain.ai/llms-full.txt", {
      headers: { "user-agent": "deepgrain-mcp/0.1" }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch corpus: ${res.status}` }],
        isError: true
      };
    }
    const text = await res.text();
    const sections = text.split(/(?=\nURL: https?:\/\/[^\n]+)/g);
    const q = query.toLowerCase();
    const hits = [];
    for (const section of sections) {
      const idx = section.toLowerCase().indexOf(q);
      if (idx === -1) continue;
      const urlMatch = section.match(/URL:\s*(\S+)/);
      const titleMatch = section.match(/^#\s+(.+)$/m);
      const start = Math.max(0, idx - 120);
      const end = Math.min(section.length, idx + q.length + 180);
      hits.push({
        url: urlMatch?.[1] ?? "(unknown)",
        title: titleMatch?.[1]?.trim() ?? "(untitled)",
        snippet: section.slice(start, end).replace(/\s+/g, " ").trim()
      });
      if (hits.length >= max) break;
    }
    if (hits.length === 0) {
      return { content: [{ type: "text", text: `No matches for "${query}".` }] };
    }
    const rendered = hits.map((h, i) => `${i + 1}. ${h.title}
   ${h.url}
   \u2026${h.snippet}\u2026`).join("\n\n");
    return {
      content: [{ type: "text", text: rendered }],
      structuredContent: { hits }
    };
  }
});

// src/lib/mcp/tools/fetch-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var fetch_article_default = defineTool2({
  name: "fetch_article",
  title: "Fetch a Deepgrain article",
  description: "Fetch a Deepgrain page by URL or an Intelligence article by slug. Returns the raw HTML so the caller can parse or cite it.",
  inputSchema: {
    urlOrSlug: z2.string().min(1).describe(
      "A full https://deepgrain.ai URL, or an Intelligence article slug like 'ai-operating-ladder-five-tiers'."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ urlOrSlug }) => {
    let target;
    if (/^https?:\/\//i.test(urlOrSlug)) {
      const parsed = new URL(urlOrSlug);
      if (!/(^|\.)deepgrain\.ai$/i.test(parsed.hostname)) {
        return {
          content: [
            { type: "text", text: "Only deepgrain.ai URLs are allowed." }
          ],
          isError: true
        };
      }
      target = parsed.toString();
    } else {
      const slug = urlOrSlug.replace(/^\/+/, "").replace(/\/+$/, "");
      target = `https://deepgrain.ai/intelligence/${slug}`;
    }
    const res = await fetch(target, {
      headers: { "user-agent": "deepgrain-mcp/0.1" },
      redirect: "follow"
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch ${target}: ${res.status}` }],
        isError: true
      };
    }
    const html = await res.text();
    return {
      content: [{ type: "text", text: html.slice(0, 2e5) }],
      structuredContent: { url: target, status: res.status }
    };
  }
});

// src/lib/mcp/tools/list-pillars.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var PILLARS = [
  {
    slug: "what-is-an-ai-operating-system",
    title: "What is an AI operating system",
    url: "https://deepgrain.ai/intelligence/what-is-an-ai-operating-system"
  },
  {
    slug: "five-pillars-of-ai-readiness",
    title: "The five pillars of AI readiness",
    url: "https://deepgrain.ai/intelligence/five-pillars-of-ai-readiness"
  },
  {
    slug: "ai-operating-ladder-five-tiers",
    title: "The AI operating ladder: five tiers",
    url: "https://deepgrain.ai/intelligence/ai-operating-ladder-five-tiers"
  },
  {
    slug: "setting-up-your-ai-workspace",
    title: "Setting up your AI workspace",
    url: "https://deepgrain.ai/intelligence/people-ops/setting-up-your-ai-workspace"
  }
];
var list_pillars_default = defineTool3({
  name: "list_pillars",
  title: "List Deepgrain pillar essays",
  description: "List the canonical Deepgrain pillar essays. Use this as the entry point when a caller wants an overview of the Deepgrain point of view before drilling into specific articles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: PILLARS.map((p, i) => `${i + 1}. ${p.title}
   ${p.url}`).join("\n\n")
      }
    ],
    structuredContent: { pillars: PILLARS }
  })
});

// src/lib/mcp/index.ts
var projectRef = "todgunffzlopbenewfnp";
var mcp_default = defineMcp({
  name: "deepgrain-mcp",
  title: "Deepgrain Intelligence",
  version: "0.1.0",
  instructions: "Tools for searching and reading the Deepgrain Intelligence library at deepgrain.ai. Sign in with your Deepgrain account to connect. Use `list_pillars` for orientation, `search_intelligence` to find articles by keyword, and `fetch_article` to read a specific page.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_intelligence_default, fetch_article_default, list_pillars_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
